name: course-project
version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-course
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: course-service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis-course
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: