server:
  port: 8080
  servlet:
    context-path: /project
spring:
  profiles:
    active: dev
  application:
     name: course-web-be
  datasource:
    url: ${SQL_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  main:
    allow-bean-definition-overriding: true
jwt:
  secret-key: ${SECRET_KEY}
  access-token-expiration : ${ACCESS_TOKEN_EX}
  refresh-token-expiration : ${REFRESH_TOKEN_EX}
