SQL_URL=jdbc:mysql://localhost:3306/project-2
USER_NAME=root
PASSWORD=123456789
SECRET_KEY=7f6ca412f8744a0c5f72881ec106c4041fd36a9066541360dd8d405d454e1b68a358c79716ab6870bcf814a0a9966ebed8639d3f3abdab027068fe93c43f34a6
REDIS_HOST=localhost
REDIS_PORT=6379
ACCESS_TOKEN_EX=259200000
REFRESH_TOKEN_EX=604800000
# Production values:
# ACCESS_TOKEN_EX = 259200000
# REFRESH_TOKEN_EX = 604800000
BUCKET_NAME=my-course-webapp-2025
ACCESS_KEY=AKIAWMDXILMFXGQ5IC73
SECRET_ACCESS_KEY=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
GOOGLE_CLIENT_ID=121852921364-eipdrl0m9a6qsft95htfdkn6t5dtmsov.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
#GOOGLE_REDIRECT_URI=http://localhost:8080/oauth2/callback
GOOGLE_REDIRECT_URI=http://localhost:3000/oauth2/callback

# VNPay Configuration
VNPAY_TMNCODE=GTOIEZAT
VNPAY_HASHSECRET=J11WUJXLYL1PWH250ZZI9AD8ZU95VEU7
VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
VNPAY_RETURNURL=http://localhost:3000/payment/return
VNPAY_APIURL=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

BREVO_API_KEY=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
BREVO_URL=https://api.brevo.com
SENDER_NAME= Kobi
SENDER_EMAIL= loint.24ite@vku.udn.vn

